# Generated by Django 2.1.1 on 2019-04-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hello_world',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
