# Generated by Django 2.1.1 on 2019-04-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_hello_world'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=49, max_length=20),
            preserve_default=False,
        ),
    ]
