# Generated by Django 2.1.1 on 2018-10-29 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_posted',
            new_name='date_created',
        ),
    ]
