# Generated by Django 2.1.1 on 2018-10-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181029_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='topic',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
