# Generated by Django 2.1.1 on 2018-10-29 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='img_path',
            new_name='article_img',
        ),
    ]
