# Generated by Django 2.1.1 on 2018-10-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181029_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_img',
            field=models.ImageField(default='default.jpg', upload_to='article_pics'),
        ),
    ]
