# Generated by Django 2.1.1 on 2018-10-29 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181029_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='article_field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Article'),
            preserve_default=False,
        ),
    ]
