# Generated by Django 2.1.1 on 2018-11-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_article_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_img',
            field=models.ImageField(default='default.jpg', upload_to='article_pics', verbose_name='Formate: jpg, gif, bmp'),
        ),
    ]
