# Generated by Django 2.1.1 on 2018-11-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20181107_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='web_mode',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
