# Generated by Django 2.1.1 on 2018-11-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_web_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='theme',
            field=models.CharField(default=100, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='theme',
            field=models.CharField(default=100, max_length=4),
            preserve_default=False,
        ),
    ]
