# Generated by Django 2.1.1 on 2018-11-13 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0011_auto_20181112_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_mode', models.CharField(max_length=3)),
                ('topic', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('teaser', models.CharField(max_length=200)),
                ('theme_img', models.ImageField(default='default.jpg', upload_to='theme_pics', verbose_name='Formate: jpg, gif, bmp')),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
