# Generated by Django 2.1.1 on 2018-11-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='importance',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='importance',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='importance',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
