# Generated by Django 2.1.1 on 2018-12-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20181115_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img_capt',
            field=models.CharField(default='Image', max_length=25),
            preserve_default=False,
        ),
    ]
