# Generated by Django 2.1.1 on 2018-12-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_article_img_capt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img_capt',
            field=models.CharField(max_length=45),
        ),
    ]
