# Generated by Django 2.1.1 on 2019-06-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_article_obj_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='obj_type',
            field=models.CharField(default='press', max_length=10),
        ),
    ]
