# Generated by Django 2.2.5 on 2019-09-14 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameId', models.CharField(default='0', max_length=5)),
                ('gameName', models.CharField(default='0', max_length=10)),
                ('gameImage', models.ImageField(default='faceDefault.jpg', upload_to='chess_pics', verbose_name='Formate: jpg, gif, bmp')),
                ('computerPlayer', models.CharField(choices=[('Black', 'White')], max_length=5)),
                ('activePlayer', models.CharField(choices=[('Black', 'White')], max_length=5)),
                ('gameStatus', models.CharField(choices=[('active', 'active'), ('won', 'won'), ('lost', 'lost'), ('gaveup', 'gamveup')], max_length=5)),
                ('activeBoard', models.TextField(max_length=800)),
                ('crateDate', models.DateTimeField(auto_now_add=True)),
                ('changeDate', models.DateTimeField(auto_now=True)),
                ('userName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
