# Generated by Django 2.2.5 on 2019-09-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chess',
            name='activePlayer',
            field=models.CharField(choices=[('Black', 'Black'), ('White', 'White')], max_length=5),
        ),
        migrations.AlterField(
            model_name='chess',
            name='computerPlayer',
            field=models.CharField(choices=[('Black', 'Black'), ('White', 'White')], max_length=5),
        ),
        migrations.AlterField(
            model_name='chess',
            name='gameStatus',
            field=models.CharField(choices=[('active', 'active'), ('won', 'won'), ('lost', 'lost'), ('gaveup', 'gamveup')], max_length=6),
        ),
    ]
