# Generated by Django 2.2.5 on 2019-09-14 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0002_auto_20190914_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chess',
            name='userName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
