# Generated by Django 2.2.5 on 2019-09-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0004_auto_20190918_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chess',
            name='gameStatus',
            field=models.CharField(choices=[('active', 'active'), ('initial', 'initial'), ('won', 'won'), ('lost', 'lost'), ('gaveup', 'gamveup')], max_length=6),
        ),
    ]
