# Generated by Django 2.2.5 on 2019-09-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0006_auto_20190918_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='chess',
            name='moves',
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chess',
            name='boardText',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='chess',
            name='gameImage',
            field=models.ImageField(default='chessboard_oFsGPaG.jpg', upload_to='chess_pics', verbose_name='Formate: jpg, gif, bmp'),
        ),
    ]
