# Generated by Django 2.2.5 on 2019-09-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0007_auto_20190918_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chess',
            name='moves',
            field=models.TextField(max_length=1000),
        ),
    ]
