# Generated by Django 2.2.5 on 2019-09-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0008_auto_20190919_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chess',
            name='boardText',
            field=models.TextField(max_length=700),
        ),
    ]
