# Generated by Django 2.2.5 on 2019-09-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0009_auto_20190919_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chess',
            name='boardText',
            field=models.TextField(max_length=900),
        ),
    ]
