# Generated by Django 2.2.5 on 2019-09-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0011_auto_20190919_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chess',
            name='activePlayer',
            field=models.CharField(choices=[('2', 'Black'), ('1', 'White')], max_length=5),
        ),
        migrations.AlterField(
            model_name='chess',
            name='computerPlayer',
            field=models.CharField(choices=[('2', 'Black'), ('1', 'White')], max_length=5),
        ),
    ]
