# Generated by Django 2.2.5 on 2019-09-24 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0012_auto_20190920_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chess',
            name='gameId',
        ),
    ]
