# Generated by Django 2.2.5 on 2019-09-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0013_remove_chess_gameid'),
    ]

    operations = [
        migrations.AddField(
            model_name='chess',
            name='removed',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
