# Generated by Django 2.2.5 on 2019-09-24 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0014_chess_removed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chess',
            old_name='computerPlayer',
            new_name='playerColor',
        ),
    ]
