# Generated by Django 2.2.5 on 2019-09-25 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0015_auto_20190924_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chess',
            old_name='removed',
            new_name='removeds',
        ),
    ]
