# Generated by Django 2.2.5 on 2019-09-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0017_auto_20190925_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='chess',
            name='rochPara',
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
